version: "3"

services:
  mysql:
    image: mariadb:10
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql:docker'
    ports:
      - 127.0.0.1:3306:3306
  laravel:
    build: '.'
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./:/app
    command: php artisan serve --host=0.0.0.0
  composer:
    image: composer
    command: sleep infinity
    volumes:
      - './:/app'
