version: "3"

services:
  mysql:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'
    ports:
      - 127.0.0.1:3306:3306
